name: Validate Configuration

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'electron/**'

jobs:
  validate:
    name: Validate Workflow Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate package.json
      run: |
        node -e "const pkg = require('./package.json'); console.log('✅ package.json is valid JSON'); console.log('Package name:', pkg.name); console.log('Version:', pkg.version);"
        
    - name: Validate workflow YAML files
      run: |
        for file in .github/workflows/*.yml; do
          echo "Validating $file..."
          node -e "
            const yaml = require('js-yaml');
            const fs = require('fs');
            try {
              yaml.load(fs.readFileSync('$file', 'utf8'));
              console.log('✅ $file is valid');
            } catch (e) {
              console.error('❌ $file has syntax error:', e.message);
              process.exit(1);
            }
          "
        done
        
    - name: Check electron-builder configuration
      run: |
        npx electron-builder --help > /dev/null && echo "✅ electron-builder is available"